// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkSyG3AHe-Wcmx4C5Vz2qfPAzFO8Wn6rc',
    appId: '1:78199655331:web:c07894628c4118e17fe816',
    messagingSenderId: '78199655331',
    projectId: 'waste-managemet-app',
    authDomain: 'waste-managemet-app.firebaseapp.com',
    storageBucket: 'waste-managemet-app.firebasestorage.app',
    measurementId: 'G-89ZGZTQMQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZFjBbFboGkQWOMNbKZDUdBTzRyu1ePC0',
    appId: '1:78199655331:android:e809b2d84b1406f87fe816',
    messagingSenderId: '78199655331',
    projectId: 'waste-managemet-app',
    storageBucket: 'waste-managemet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXn0Jx3eNNXZkj5i8q9-vUbu1ipZcWX5Y',
    appId: '1:78199655331:ios:3fef591befac43c57fe816',
    messagingSenderId: '78199655331',
    projectId: 'waste-managemet-app',
    storageBucket: 'waste-managemet-app.firebasestorage.app',
    iosBundleId: 'com.example.wasteManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXn0Jx3eNNXZkj5i8q9-vUbu1ipZcWX5Y',
    appId: '1:78199655331:ios:3fef591befac43c57fe816',
    messagingSenderId: '78199655331',
    projectId: 'waste-managemet-app',
    storageBucket: 'waste-managemet-app.firebasestorage.app',
    iosBundleId: 'com.example.wasteManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkSyG3AHe-Wcmx4C5Vz2qfPAzFO8Wn6rc',
    appId: '1:78199655331:web:7a57efe1c814f5c27fe816',
    messagingSenderId: '78199655331',
    projectId: 'waste-managemet-app',
    authDomain: 'waste-managemet-app.firebaseapp.com',
    storageBucket: 'waste-managemet-app.firebasestorage.app',
    measurementId: 'G-VH2X8CTXHV',
  );
}
